# Generated by Django 3.1.2 on 2020-12-08 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comunidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Delegada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300, null=True)),
                ('comunidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comunidades.comunidad')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('descripción', models.CharField(max_length=1000, null=True)),
                ('alto', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('ancho', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('profundidad', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('diámetro', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('color', models.CharField(max_length=100, null=True)),
                ('tejido', models.CharField(max_length=100, null=True)),
                ('imagen', models.ImageField(upload_to='comunidades')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creación', models.DateTimeField(auto_now_add=True, null=True)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Solicitado', 'Solicitado'), ('Confirmado', 'Confirmado'), ('Finalizado', 'Finalizado')], max_length=20, null=True)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('delegada', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comunidades.delegada')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comunidades.producto')),
            ],
        ),
        migrations.AddField(
            model_name='comunidad',
            name='productos',
            field=models.ManyToManyField(to='comunidades.Producto'),
        ),
    ]
